### ISSUE TITLE
No module named 'munch'

### ISSUE THREAD

**Issue by thedemoncat** [haxorof/docker-openstack-cli#174]
Running the command gives an error:
docker run -it --rm -v $(pwd)/.config/openstack :/etc/openstack haxorof/openstack-cli --os-cloud horizon server list

`
Could not load 'loadbalancer_amphora_configure': No module named 'munch'
Could not load 'loadbalancer_amphora_delete': No module named 'munch'
Could not load 'loadbalancer_amphora_failover': No module named 'munch'       
Could not load 'loadbalancer_amphora_list': No module named 'munch'
Could not load 'loadbalancer_amphora_show': No module named 'munch'
Could not load 'loadbalancer_amphora_stats_show': No module named 'munch'     
Could not load 'loadbalancer_availabilityzone_create': No module named 'munch'
Could not load 'loadbalancer_availabilityzone_delete': No module named 'munch'
Could not load 'loadbalancer_availabilityzone_list': No module named 'munch'  
Could not load 'loadbalancer_availabilityzone_set': No module named 'munch'
Could not load 'loadbalancer_availabilityzone_show': No module named 'munch'
Could not load 'loadbalancer_availabilityzone_unset': No module named 'munch'
Could not load 'loadbalancer_availabilityzoneprofile_create': No module named 'munch'
Could not load 'loadbalancer_availabilityzoneprofile_delete': No module named 'munch'
Could not load 'loadbalancer_availabilityzoneprofile_list': No module named 'munch'
Could not load 'loadbalancer_availabilityzoneprofile_set': No module named 'munch'
Could not load 'loadbalancer_availabilityzoneprofile_show': No module named 'munch'
Could not load 'loadbalancer_create': No module named 'munch'
Could not load 'loadbalancer_delete': No module named 'munch'
Could not load 'loadbalancer_failover': No module named 'munch'
Could not load 'loadbalancer_flavor_create': No module named 'munch'
Could not load 'loadbalancer_flavor_delete': No module named 'munch'
Could not load 'loadbalancer_flavor_list': No module named 'munch'
Could not load 'loadbalancer_flavor_set': No module named 'munch'
Could not load 'loadbalancer_flavor_show': No module named 'munch'
Could not load 'loadbalancer_flavor_unset': No module named 'munch'
Could not load 'loadbalancer_flavorprofile_create': No module named 'munch'
Could not load 'loadbalancer_flavorprofile_delete': No module named 'munch'
Could not load 'loadbalancer_flavorprofile_list': No module named 'munch'
Could not load 'loadbalancer_flavorprofile_set': No module named 'munch'
Could not load 'loadbalancer_flavorprofile_show': No module named 'munch'
Could not load 'loadbalancer_healthmonitor_create': No module named 'munch'
Could not load 'loadbalancer_healthmonitor_delete': No module named 'munch'
Could not load 'loadbalancer_healthmonitor_list': No module named 'munch'
Could not load 'loadbalancer_healthmonitor_set': No module named 'munch'
Could not load 'loadbalancer_healthmonitor_show': No module named 'munch'
Could not load 'loadbalancer_healthmonitor_unset': No module named 'munch'
Could not load 'loadbalancer_l7policy_create': No module named 'munch'
Could not load 'loadbalancer_l7policy_delete': No module named 'munch'
Could not load 'loadbalancer_l7policy_list': No module named 'munch'
Could not load 'loadbalancer_l7policy_set': No module named 'munch'
Could not load 'loadbalancer_l7policy_show': No module named 'munch'
Could not load 'loadbalancer_l7policy_unset': No module named 'munch'
Could not load 'loadbalancer_l7rule_create': No module named 'munch'
Could not load 'loadbalancer_l7rule_delete': No module named 'munch'
Could not load 'loadbalancer_l7rule_list': No module named 'munch'
Could not load 'loadbalancer_l7rule_set': No module named 'munch'
Could not load 'loadbalancer_l7rule_show': No module named 'munch'
Could not load 'loadbalancer_l7rule_unset': No module named 'munch'
Could not load 'loadbalancer_list': No module named 'munch'
Could not load 'loadbalancer_listener_create': No module named 'munch'
Could not load 'loadbalancer_listener_delete': No module named 'munch'
Could not load 'loadbalancer_listener_list': No module named 'munch'
Could not load 'loadbalancer_listener_set': No module named 'munch'
Could not load 'loadbalancer_listener_show': No module named 'munch'
Could not load 'loadbalancer_listener_stats_show': No module named 'munch'
Could not load 'loadbalancer_listener_unset': No module named 'munch'
Could not load 'loadbalancer_member_create': No module named 'munch'
Could not load 'loadbalancer_member_delete': No module named 'munch'
Could not load 'loadbalancer_member_list': No module named 'munch'
Could not load 'loadbalancer_member_set': No module named 'munch'
Could not load 'loadbalancer_member_show': No module named 'munch'
Could not load 'loadbalancer_member_unset': No module named 'munch'
Could not load 'loadbalancer_pool_create': No module named 'munch'
Could not load 'loadbalancer_pool_delete': No module named 'munch'
Could not load 'loadbalancer_pool_list': No module named 'munch'
Could not load 'loadbalancer_pool_set': No module named 'munch'
Could not load 'loadbalancer_pool_show': No module named 'munch'
Could not load 'loadbalancer_pool_unset': No module named 'munch'
Could not load 'loadbalancer_provider_capability_list': No module named 'munch'
Could not load 'loadbalancer_provider_list': No module named 'munch'
Could not load 'loadbalancer_quota_defaults_show': No module named 'munch'
Could not load 'loadbalancer_quota_list': No module named 'munch'
Could not load 'loadbalancer_quota_reset': No module named 'munch'
Could not load 'loadbalancer_quota_set': No module named 'munch'
Could not load 'loadbalancer_quota_show': No module named 'munch'
Could not load 'loadbalancer_quota_unset': No module named 'munch'
Could not load 'loadbalancer_set': No module named 'munch'
Could not load 'loadbalancer_show': No module named 'munch'
Could not load 'loadbalancer_stats_show': No module named 'munch'
Could not load 'loadbalancer_status_show': No module named 'munch'
Could not load 'loadbalancer_unset': No module named 'munch'
`

**Comment by haxorof** [comment]
Thanks for reporting this. Will have a look at it.
